# fly.toml file generated for calendlex on 2023-04-06T22:58:55+02:00

app = "calendlex"
kill_signal = "SIGTERM"
kill_timeout = 5
mounts = []
primary_region = "cdg"
processes = []

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "calendlex.fly.dev"
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
